name: Go

on:
  push:
    branches: 
    - main
    - release/*
    - devs/*
  pull_request:
    branches: 
    - main
    - release/*
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 2,14 * * *'
  release:
    types: # This configuration does not affect the page_build event above
      - created

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    #- name: Test
    #  run: go test -v ./...
